### PR TITLE
PR: Command e to move to end of current word

### PR DESCRIPTION
**Pull request by mariacamilarg**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, thanks a lot for keep contributing to `spyder-vim`!!

Please add a test for this new command in

https://github.com/spyder-ide/spyder-vim/blob/master/spyder_vim/tests/test_vim.py

**Comment by ccordoba12** [comment]
@bgallois, could you finish this one by rebasing it and adding a test for it?

**Comment by bgallois** [comment]
@ccordoba12, I added tests for the e command and fixed tests and behavior for the related w and b commands.

**Comment by goanpeca** [comment]
Thanks for working on this @bgallois 🥳

**Pull request merged**
