### PR TITLE
Commands p, P, u fixed/added and clipboard selection type is tracked

### LINKED ISSUE #13: When you yank a whole line, p (for "put" or "paste") should put the line on a new line.
So, let's say my cursor is in the middle of the line.  Then, when I'm in escape mode and hit "yy", your plugin properly copies the whole line.  But in vim, when I hit "p", it's supposed to paste this to a newline, not in the middle of the line that my cursor is currently at, which your plugin currently does.  When I hit "p" after just hitting "y" on some visually selected text, it is supposed to "put" (or "paste," if you like) the text at (or just after) the current cursor position, on the same line.  But not when hitting "p" after "yy".

To achieve the effect I'm used to, I have to hit "yy", then "o" (to open a new line), then "p".

Thanks for your free labor, regardless :-)

### PR DESCRIPTION
**Pull request by pwoosam**
Fixes #13 

----

Command u updates cursor after undo.
Command p fixed
Command P added

Also I believe there is another bug in u. The normal undo behavior in vim appears to set the cursor to the position of cursor before the last change took place, not the position of the last change.

### CODE REVIEW

**Comment by pwoosam** [comment]
@Nodd This kind of works for now, but it'll have some issues with pasting multiple lines as a block since it doesn't see it as a block selection. It treats it as a character selection instead. I believe vim had its own clipboard that kept track of the different types of selections (block, line, and character).

**Comment by Nodd** [comment]
vim has to work with external copy/paste too (typically, middle click of the mouse on Linux), I don't know how it's managed. It should be possible to record internally the type of selection when pasting?
Anyway I'm not a regular vim user so you know better than me how it works!

**Comment by pwoosam** [comment]
It handles the the external copy/paste as if they were a selection of characters. So it would have the same behavior as this PR does when it pastes multiple lines.

I'm not sure what the best way of keeping track of the selection type since QClipboard can't be subclassed.

I suppose a class with two properties, one clipboard and one string to keep track of the type would work?

**Comment by pwoosam** [comment]
@Nodd, check out the latest commit. It keeps track of the selection type now and has the same vim behaviors for p and P that you'd expect. 👍

**Comment by pwoosam** [comment]
@Nodd I also have implemented visual mode and some of its commands. But this PR should be merged first to take advantage of visual mode.

**Comment by ccordoba12** [comment]
@pwoosam, I invited you to be collaborator on this repo. This means you'll be able to tag, edit, and merge/close issues and pull requests.

Since you're very interested in the progress of `spyder-vim`, I want to trust on you and give you the freedom to keep working on this without waiting for @Nodd to review/merge your work.

So feel free to merge this and the other PRs you have submitted whenever you consider they are ready. I'm sure @Nodd will leave you comments in case he finds it necessary. For that, I only recommend you to always create PRs for your work, instead of submitting it directly to master.

Of course, if you want me to review your work, don't hesitate to ping me (although my knowledge of Vim is almost zilch ;-)

**Comment by ccordoba12** [comment]
And don't forget to mark the commands you implement on each PR on issue #1 ;-)

**Comment by pwoosam** [comment]
@ccordoba12 Thank you for inviting me to be a collaborator on this repo! I'll be sure to ping you if I need any help reviewing my work.

It's always a pleasure to contribute :)

**Pull request merged**
