### PR TITLE
Add features

### PR DESCRIPTION
**Pull request by bgallois**
Add new commands #1
* Fixed the "dd" command not working on the last line.
* Added the "d" command to delete the selection.
* Added the arrow keys navigation in Visual mode.

### CODE REVIEW

**Comment by goanpeca** [comment]
@bgallois are you familiar with Github Actions? One pending work we have is to move this to Github actions so we can test on all platforms (Macos, Win and Linux) in a single CI system

**Comment by bgallois** [comment]
@goanpeca yes I will do it. I will simplify the development process.

**Comment by goanpeca** [comment]
See https://github.com/spyder-ide/spyder/tree/master/.github/workflows

**Comment by ccordoba12** [comment]
> @goanpeca yes I will do it. I will simplify the development process.

Great! Thanks a lot for that!

We'll grant you write permissions to this repo then, because the only way to test Github Actions in a PR is by using an in-repo branch.

**Pull request merged**
