### PR TITLE
PR: Move CI to GitHub actions

### PR DESCRIPTION
**Pull request by bgallois**

### CODE REVIEW

**Comment by goanpeca** [comment]
Awesome work @bgallois !

It seems we have a failing test on window 

`spyder_vim/tests/test_vim.py::test_p_command_char_mode FAILED `

Do you have access to a [Windows VM](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) to try to debug the problem?

Thanks for putting this together.

**Comment by goanpeca** [comment]
(I have disabled Circle CI so on the next push that failing check should go away.)

**Comment by bgallois** [comment]
@goanpeca I'm investigating the Windows failing test. Performed manually in Spyder the test is successful but performed by pytest an extra blank space is added at the beginning of the selected text. Still working on it.

**Comment by goanpeca** [comment]
>@goanpeca I'm investigating the Windows failing test. Performed manually in Spyder the test is successful but performed by pytest an extra blank space is added at the beginning of the selected text. Still working on it.

Yeah, this sometimes happens, let's add a skip if the test runs on windows and on CI, so that local tests on windows can still be run.

**Comment by goanpeca** [comment]
Something like:

```python
@pytest.mark.skipif(os.name == 'nt' and bool(os.environ('CI')), reason="Does not work on windows CI!")
```

**Pull request merged**
